import type { Metadata } from "next";
import { GeistSans } from "geist/font/sans";
import { GeistMono } from "geist/font/mono";
import "./globals.css";
import PrivyProviderWrapper from "@/components/privy-provider-wrapper";
import Navbar from "@/components/Navbar";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body suppressHydrationWarning={true} className={`${GeistMono.className} moving-gradient h-screen`}>
        <PrivyProviderWrapper>
          <>
            <Navbar />
            {children}
          </>
        </PrivyProviderWrapper>
      </body>
    </html>
  );
}
